ventory:
    plugin: SimpleInventory
    options:
        host_file: "C:/Users/MaYiCk-GiO-DC/Desktop/U3.3-Python-Nornir-IOS-XR/hosts.yaml"
        group_file: "C:/Users/MaYiCk-GiO-DC/Desktop/U3.3-Python-Nornir-IOS-XR/groups.yaml"
nner:
plugin: threaded
options:
    num_workers: 20